D4rkcide
BITCORNProject/BITCORNData pull request #32
Opened 2020-02-16 19:23 UTC by JasonSowers

2020-02-16 19:23 UTC, JasonSowers commented
do not merge yet as it will take a bit to test and get into production

2020-02-22 21:21 UTC, SamuliSalonen requested changes

2020-02-22 21:21 UTC, SamuliSalonen commented on BITCORNService/Utils/ReferralUtils.cs
> +            int? userId =0;
this functionality already exists in util
`int? userId = BitcornUtils.GetUserForPlatform(platformId, dbContext).Select(u => u.UserId).FirstOrDefault();`

2020-02-22 21:21 UTC, SamuliSalonen commented on BITCORNService/Utils/ReferralUtils.cs
> +                }
changes are never saved to the database

2020-02-22 21:22 UTC, SamuliSalonen commented on BITCORNService/Utils/ReferralUtils.cs
> +            }
this functionality already exists in util
`int? userId = BitcornUtils.GetUserForPlatform(platformId, dbContext).Select(u => u.UserId).FirstOrDefault();`

2020-02-23 10:59 UTC, SamuliSalonen approved these changes
:shipit:

2020-02-23 17:38 UTC, SamuliSalonen approved these changes

2020-02-23 17:55 UTC, merged